// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, RequestResult, TDataShape } from './client';
import { client } from './client.gen';
import type { PostsAllEventPostsAllJobIdGetData, PostsAllEventPostsAllJobIdGetErrors, PostsAllEventPostsAllJobIdGetResponses, PostsAllPostsAllJobPostData, PostsAllPostsAllJobPostErrors, PostsAllPostsAllJobPostResponses, PostsSavePostsSavePostData, PostsSavePostsSavePostErrors, PostsSavePostsSavePostResponses, StoriesOrHighlightsStoriesSavePostData, StoriesOrHighlightsStoriesSavePostErrors, StoriesOrHighlightsStoriesSavePostResponses, TestTestGetData, TestTestGetResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Stories Or Highlights
 *
 * Download stories as well as highlights
 */
export const storiesOrHighlightsStoriesSavePost = <ThrowOnError extends boolean = false>(options: Options<StoriesOrHighlightsStoriesSavePostData, ThrowOnError>): RequestResult<StoriesOrHighlightsStoriesSavePostResponses, StoriesOrHighlightsStoriesSavePostErrors, ThrowOnError> => (options.client ?? client).post<StoriesOrHighlightsStoriesSavePostResponses, StoriesOrHighlightsStoriesSavePostErrors, ThrowOnError>({
    url: '/stories/save',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Posts Save
 *
 * Download 'post' and 'reels'
 */
export const postsSavePostsSavePost = <ThrowOnError extends boolean = false>(options: Options<PostsSavePostsSavePostData, ThrowOnError>): RequestResult<PostsSavePostsSavePostResponses, PostsSavePostsSavePostErrors, ThrowOnError> => (options.client ?? client).post<PostsSavePostsSavePostResponses, PostsSavePostsSavePostErrors, ThrowOnError>({
    url: '/posts/save',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Posts All
 */
export const postsAllPostsAllJobPost = <ThrowOnError extends boolean = false>(options: Options<PostsAllPostsAllJobPostData, ThrowOnError>): RequestResult<PostsAllPostsAllJobPostResponses, PostsAllPostsAllJobPostErrors, ThrowOnError> => (options.client ?? client).post<PostsAllPostsAllJobPostResponses, PostsAllPostsAllJobPostErrors, ThrowOnError>({
    url: '/posts/all/job',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Posts All Event
 */
export const postsAllEventPostsAllJobIdGet = <ThrowOnError extends boolean = false>(options: Options<PostsAllEventPostsAllJobIdGetData, ThrowOnError>): RequestResult<PostsAllEventPostsAllJobIdGetResponses, PostsAllEventPostsAllJobIdGetErrors, ThrowOnError> => (options.client ?? client).get<PostsAllEventPostsAllJobIdGetResponses, PostsAllEventPostsAllJobIdGetErrors, ThrowOnError>({ url: '/posts/all/{job_id}', ...options });

/**
 * Test
 */
export const testTestGet = <ThrowOnError extends boolean = false>(options?: Options<TestTestGetData, ThrowOnError>): RequestResult<TestTestGetResponses, unknown, ThrowOnError> => (options?.client ?? client).get<TestTestGetResponses, unknown, ThrowOnError>({ url: '/test', ...options });
