// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, RequestResult, TDataShape } from './client';
import { client } from './client.gen';
import type { PostsSavePostsSaveGetData, PostsSavePostsSaveGetErrors, PostsSavePostsSaveGetResponses, StoriesOrHighlightsStoriesSaveGetData, StoriesOrHighlightsStoriesSaveGetErrors, StoriesOrHighlightsStoriesSaveGetResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Stories Or Highlights
 *
 * Download stories as well as highlights
 */
export const storiesOrHighlightsStoriesSaveGet = <ThrowOnError extends boolean = false>(options: Options<StoriesOrHighlightsStoriesSaveGetData, ThrowOnError>): RequestResult<StoriesOrHighlightsStoriesSaveGetResponses, StoriesOrHighlightsStoriesSaveGetErrors, ThrowOnError> => (options.client ?? client).get<StoriesOrHighlightsStoriesSaveGetResponses, StoriesOrHighlightsStoriesSaveGetErrors, ThrowOnError>({ url: '/stories/save', ...options });

/**
 * Posts Save
 *
 * Download 'post' and 'reels'
 */
export const postsSavePostsSaveGet = <ThrowOnError extends boolean = false>(options: Options<PostsSavePostsSaveGetData, ThrowOnError>): RequestResult<PostsSavePostsSaveGetResponses, PostsSavePostsSaveGetErrors, ThrowOnError> => (options.client ?? client).get<PostsSavePostsSaveGetResponses, PostsSavePostsSaveGetErrors, ThrowOnError>({ url: '/posts/save', ...options });
