// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:8000' | (string & {});
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * JobData[MultiplePostResponse]
 */
export type JobDataMultiplePostResponse = {
    /**
     * Event
     */
    event: 'progress' | 'completed' | 'error';
    /**
     * Completed
     */
    completed?: number | number | null;
    /**
     * Total
     */
    total?: number | number | null;
    data?: MultiplePostResponse | null;
};

/**
 * MultiplePostItem
 */
export type MultiplePostItem = {
    /**
     * Id
     */
    id?: string | number | null;
    cover_media?: PostMediaItem | null;
    /**
     * Media
     */
    media?: Array<PostMediaItem>;
};

/**
 * MultiplePostProfileItem
 */
export type MultiplePostProfileItem = {
    /**
     * Full Name
     */
    full_name: string | null;
    /**
     * Username
     */
    username: string | null;
    /**
     * Profile Pic Url
     */
    profile_pic_url: string | null;
    /**
     * Posts
     */
    posts?: Array<MultiplePostItem>;
};

/**
 * MultiplePostResponse
 */
export type MultiplePostResponse = {
    /**
     * Result
     */
    result?: Array<MultiplePostProfileItem>;
};

/**
 * PostAllJobResponse
 */
export type PostAllJobResponse = {
    /**
     * Job Id
     */
    job_id: string;
};

/**
 * PostAllRequest
 */
export type PostAllRequest = {
    /**
     * Id
     */
    id: string;
    storage_state?: StorageState | null;
};

/**
 * PostMediaItem
 */
export type PostMediaItem = {
    /**
     * Image Url
     */
    image_url: string | null;
    /**
     * Video Url
     */
    video_url: string | null;
};

/**
 * PostProfileItem
 */
export type PostProfileItem = {
    /**
     * Full Name
     */
    full_name: string | null;
    /**
     * Username
     */
    username: string | null;
    /**
     * Profile Pic Url
     */
    profile_pic_url: string | null;
    cover_media?: PostMediaItem | null;
    /**
     * Media
     */
    media?: Array<PostMediaItem>;
};

/**
 * PostResponse
 */
export type PostResponse = {
    /**
     * Result
     */
    result?: Array<PostProfileItem>;
};

/**
 * PostSaveRequest
 */
export type PostSaveRequest = {
    /**
     * Url
     */
    url: string;
    storage_state?: StorageState | null;
};

/**
 * StorageState
 */
export const StorageState = { DATA_BEAST_JSON: 'data/beast.json', DATA_M_A_D_TEMP_JSON: 'data/m_a_d_temp.json' } as const;

/**
 * StorageState
 */
export type StorageState = typeof StorageState[keyof typeof StorageState];

/**
 * StoriesOrHighlightsRequest
 */
export type StoriesOrHighlightsRequest = {
    /**
     * Url Or Id
     */
    url_or_id: string;
    storage_state?: StorageState | null;
};

/**
 * StoryMediaItem
 */
export type StoryMediaItem = {
    /**
     * Image Url
     */
    image_url?: string | null;
    /**
     * Video Url
     */
    video_url?: string | null;
};

/**
 * StoryProfileItem
 */
export type StoryProfileItem = {
    /**
     * Username
     */
    username: string;
    /**
     * Profile Pic Url
     */
    profile_pic_url?: string | null;
    /**
     * Media
     */
    media?: Array<StoryMediaItem>;
};

/**
 * StoryResponse
 */
export type StoryResponse = {
    /**
     * Result
     */
    result?: Array<StoryProfileItem>;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

export type StoriesOrHighlightsStoriesSavePostData = {
    body: StoriesOrHighlightsRequest;
    path?: never;
    query?: never;
    url: '/stories/save';
};

export type StoriesOrHighlightsStoriesSavePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type StoriesOrHighlightsStoriesSavePostError = StoriesOrHighlightsStoriesSavePostErrors[keyof StoriesOrHighlightsStoriesSavePostErrors];

export type StoriesOrHighlightsStoriesSavePostResponses = {
    /**
     * Successful Response
     */
    200: StoryResponse;
};

export type StoriesOrHighlightsStoriesSavePostResponse = StoriesOrHighlightsStoriesSavePostResponses[keyof StoriesOrHighlightsStoriesSavePostResponses];

export type PostsSavePostsSavePostData = {
    body: PostSaveRequest;
    path?: never;
    query?: never;
    url: '/posts/save';
};

export type PostsSavePostsSavePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PostsSavePostsSavePostError = PostsSavePostsSavePostErrors[keyof PostsSavePostsSavePostErrors];

export type PostsSavePostsSavePostResponses = {
    /**
     * Successful Response
     */
    200: PostResponse;
};

export type PostsSavePostsSavePostResponse = PostsSavePostsSavePostResponses[keyof PostsSavePostsSavePostResponses];

export type PostsAllPostsAllJobPostData = {
    body: PostAllRequest;
    path?: never;
    query?: never;
    url: '/posts/all/job';
};

export type PostsAllPostsAllJobPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PostsAllPostsAllJobPostError = PostsAllPostsAllJobPostErrors[keyof PostsAllPostsAllJobPostErrors];

export type PostsAllPostsAllJobPostResponses = {
    /**
     * Successful Response
     */
    200: PostAllJobResponse;
};

export type PostsAllPostsAllJobPostResponse = PostsAllPostsAllJobPostResponses[keyof PostsAllPostsAllJobPostResponses];

export type PostsAllEventPostsAllJobIdGetData = {
    body?: never;
    path: {
        /**
         * Job Id
         */
        job_id: string;
    };
    query?: never;
    url: '/posts/all/{job_id}';
};

export type PostsAllEventPostsAllJobIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PostsAllEventPostsAllJobIdGetError = PostsAllEventPostsAllJobIdGetErrors[keyof PostsAllEventPostsAllJobIdGetErrors];

export type PostsAllEventPostsAllJobIdGetResponses = {
    /**
     * Successful Response
     */
    200: JobDataMultiplePostResponse;
};

export type PostsAllEventPostsAllJobIdGetResponse = PostsAllEventPostsAllJobIdGetResponses[keyof PostsAllEventPostsAllJobIdGetResponses];

export type TestTestGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/test';
};

export type TestTestGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};
