// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:8000' | (string & {});
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * PostMediaItem
 */
export type PostMediaItem = {
    /**
     * Image Url
     */
    image_url: string | null;
    /**
     * Video Url
     */
    video_url: string | null;
};

/**
 * PostProfileItem
 */
export type PostProfileItem = {
    /**
     * Full Name
     */
    full_name: string | null;
    /**
     * Username
     */
    username: string | null;
    /**
     * Profile Pic Url
     */
    profile_pic_url: string | null;
    cover_media?: PostMediaItem | null;
    /**
     * Media
     */
    media?: Array<PostMediaItem>;
};

/**
 * PostResponse
 */
export type PostResponse = {
    /**
     * Result
     */
    result?: Array<PostProfileItem>;
};

/**
 * StoryMediaItem
 */
export type StoryMediaItem = {
    /**
     * Image Url
     */
    image_url?: string | null;
    /**
     * Video Url
     */
    video_url?: string | null;
};

/**
 * StoryProfileItem
 */
export type StoryProfileItem = {
    /**
     * Username
     */
    username: string;
    /**
     * Profile Pic Url
     */
    profile_pic_url?: string | null;
    /**
     * Media
     */
    media?: Array<StoryMediaItem>;
};

/**
 * StoryResponse
 */
export type StoryResponse = {
    /**
     * Result
     */
    result?: Array<StoryProfileItem>;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

export type StoriesOrHighlightsStoriesSaveGetData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Url Or Id
         */
        url_or_id: string;
    };
    url: '/stories/save';
};

export type StoriesOrHighlightsStoriesSaveGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type StoriesOrHighlightsStoriesSaveGetError = StoriesOrHighlightsStoriesSaveGetErrors[keyof StoriesOrHighlightsStoriesSaveGetErrors];

export type StoriesOrHighlightsStoriesSaveGetResponses = {
    /**
     * Successful Response
     */
    200: StoryResponse;
};

export type StoriesOrHighlightsStoriesSaveGetResponse = StoriesOrHighlightsStoriesSaveGetResponses[keyof StoriesOrHighlightsStoriesSaveGetResponses];

export type PostsSavePostsSaveGetData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Url
         */
        url: string;
    };
    url: '/posts/save';
};

export type PostsSavePostsSaveGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PostsSavePostsSaveGetError = PostsSavePostsSaveGetErrors[keyof PostsSavePostsSaveGetErrors];

export type PostsSavePostsSaveGetResponses = {
    /**
     * Successful Response
     */
    200: PostResponse;
};

export type PostsSavePostsSaveGetResponse = PostsSavePostsSaveGetResponses[keyof PostsSavePostsSaveGetResponses];
