// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:8000' | (string & {});
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * JobData[MultiplePostResponse]
 */
export type JobDataMultiplePostResponse = {
    /**
     * Event
     */
    event: 'progress' | 'completed' | 'error';
    /**
     * Completed
     */
    completed?: number | number | null;
    /**
     * Total
     */
    total?: number | number | null;
    data?: MultiplePostResponse | null;
};

/**
 * MultiplePostItem
 */
export type MultiplePostItem = {
    /**
     * Id
     */
    id?: string | number | null;
    cover_media?: PostMediaItem | null;
    /**
     * Media
     */
    media?: Array<PostMediaItem>;
};

/**
 * MultiplePostProfileItem
 */
export type MultiplePostProfileItem = {
    /**
     * Full Name
     */
    full_name: string | null;
    /**
     * Username
     */
    username: string | null;
    /**
     * Profile Pic Url
     */
    profile_pic_url: string | null;
    /**
     * Posts
     */
    posts?: Array<MultiplePostItem>;
};

/**
 * MultiplePostResponse
 */
export type MultiplePostResponse = {
    /**
     * Result
     */
    result?: Array<MultiplePostProfileItem>;
};

/**
 * PostAllJobResponse
 */
export type PostAllJobResponse = {
    /**
     * Job Id
     */
    job_id: string;
};

/**
 * PostMediaItem
 */
export type PostMediaItem = {
    /**
     * Image Url
     */
    image_url: string | null;
    /**
     * Video Url
     */
    video_url: string | null;
};

/**
 * PostProfileItem
 */
export type PostProfileItem = {
    /**
     * Full Name
     */
    full_name: string | null;
    /**
     * Username
     */
    username: string | null;
    /**
     * Profile Pic Url
     */
    profile_pic_url: string | null;
    cover_media?: PostMediaItem | null;
    /**
     * Media
     */
    media?: Array<PostMediaItem>;
};

/**
 * PostResponse
 */
export type PostResponse = {
    /**
     * Result
     */
    result?: Array<PostProfileItem>;
};

/**
 * StorageState
 */
export type StorageState = 'data/beast.json';

/**
 * StoryMediaItem
 */
export type StoryMediaItem = {
    /**
     * Image Url
     */
    image_url?: string | null;
    /**
     * Video Url
     */
    video_url?: string | null;
};

/**
 * StoryProfileItem
 */
export type StoryProfileItem = {
    /**
     * Username
     */
    username: string;
    /**
     * Profile Pic Url
     */
    profile_pic_url?: string | null;
    /**
     * Media
     */
    media?: Array<StoryMediaItem>;
};

/**
 * StoryResponse
 */
export type StoryResponse = {
    /**
     * Result
     */
    result?: Array<StoryProfileItem>;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

export type StoriesOrHighlightsStoriesSaveGetData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Url Or Id
         */
        url_or_id: string;
        /**
         * Storage State
         */
        storage_state?: StorageState | null;
    };
    url: '/stories/save';
};

export type StoriesOrHighlightsStoriesSaveGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type StoriesOrHighlightsStoriesSaveGetError = StoriesOrHighlightsStoriesSaveGetErrors[keyof StoriesOrHighlightsStoriesSaveGetErrors];

export type StoriesOrHighlightsStoriesSaveGetResponses = {
    /**
     * Successful Response
     */
    200: StoryResponse;
};

export type StoriesOrHighlightsStoriesSaveGetResponse = StoriesOrHighlightsStoriesSaveGetResponses[keyof StoriesOrHighlightsStoriesSaveGetResponses];

export type PostsSavePostsSaveGetData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Url
         */
        url: string;
        /**
         * Storage State
         */
        storage_state?: StorageState | null;
    };
    url: '/posts/save';
};

export type PostsSavePostsSaveGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PostsSavePostsSaveGetError = PostsSavePostsSaveGetErrors[keyof PostsSavePostsSaveGetErrors];

export type PostsSavePostsSaveGetResponses = {
    /**
     * Successful Response
     */
    200: PostResponse;
};

export type PostsSavePostsSaveGetResponse = PostsSavePostsSaveGetResponses[keyof PostsSavePostsSaveGetResponses];

export type PostsAllPostsAllJobGetData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Id
         */
        id: string;
        /**
         * Storage State
         */
        storage_state?: StorageState | null;
    };
    url: '/posts/all/job';
};

export type PostsAllPostsAllJobGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PostsAllPostsAllJobGetError = PostsAllPostsAllJobGetErrors[keyof PostsAllPostsAllJobGetErrors];

export type PostsAllPostsAllJobGetResponses = {
    /**
     * Successful Response
     */
    200: PostAllJobResponse;
};

export type PostsAllPostsAllJobGetResponse = PostsAllPostsAllJobGetResponses[keyof PostsAllPostsAllJobGetResponses];

export type PostsAllEventPostsAllJobIdGetData = {
    body?: never;
    path: {
        /**
         * Job Id
         */
        job_id: string;
    };
    query?: never;
    url: '/posts/all/{job_id}';
};

export type PostsAllEventPostsAllJobIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PostsAllEventPostsAllJobIdGetError = PostsAllEventPostsAllJobIdGetErrors[keyof PostsAllEventPostsAllJobIdGetErrors];

export type PostsAllEventPostsAllJobIdGetResponses = {
    /**
     * Successful Response
     */
    200: JobDataMultiplePostResponse;
};

export type PostsAllEventPostsAllJobIdGetResponse = PostsAllEventPostsAllJobIdGetResponses[keyof PostsAllEventPostsAllJobIdGetResponses];

export type TestTestGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/test';
};

export type TestTestGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};
